version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Skipping 'pre_build' phase
  build:
    commands:
      - echo Package started on `date`
      - sam package --template-file sam-template.yml --output-template-file package.yml --s3-bucket sam-src-az --s3-prefix ImageUploadNotifier-src --region us-east-1
  post_build:
    commands:
      - echo Package completed on `date`
artifacts:
  files:
    - package.yml